package com.zd.testing.business.mapper;

import com.zd.testing.business.model.Supplier;
import com.zd.testing.business.model.SupplierExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SupplierMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int countByExample(SupplierExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByExample(SupplierExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insert(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insertSelective(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	List<Supplier> selectByExample(SupplierExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	Supplier selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Supplier record,
			@Param("example") SupplierExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExample(@Param("record") Supplier record,
			@Param("example") SupplierExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKeySelective(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKey(Supplier record);
}