package com.zd.testing.business.model;

import java.util.Date;

public class Inbound {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.ref
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String ref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String supplier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.contact
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.phone
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.biz_user_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer bizUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.inbound_date
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Date inboundDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.manager_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.status
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double moneyWithTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.id
	 * @return  the value of inbound.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.id
	 * @param id  the value for inbound.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.ref
	 * @return  the value of inbound.ref
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getRef() {
		return ref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.ref
	 * @param ref  the value for inbound.ref
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setRef(String ref) {
		this.ref = ref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.supplier
	 * @return  the value of inbound.supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.supplier
	 * @param supplier  the value for inbound.supplier
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.contact
	 * @return  the value of inbound.contact
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.contact
	 * @param contact  the value for inbound.contact
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.phone
	 * @return  the value of inbound.phone
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.phone
	 * @param phone  the value for inbound.phone
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.biz_user_id
	 * @return  the value of inbound.biz_user_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getBizUserId() {
		return bizUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.biz_user_id
	 * @param bizUserId  the value for inbound.biz_user_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setBizUserId(Integer bizUserId) {
		this.bizUserId = bizUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.inbound_date
	 * @return  the value of inbound.inbound_date
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Date getInboundDate() {
		return inboundDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.inbound_date
	 * @param inboundDate  the value for inbound.inbound_date
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setInboundDate(Date inboundDate) {
		this.inboundDate = inboundDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.manager_id
	 * @return  the value of inbound.manager_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.manager_id
	 * @param managerId  the value for inbound.manager_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.status
	 * @return  the value of inbound.status
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.status
	 * @param status  the value for inbound.status
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.money
	 * @return  the value of inbound.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.money
	 * @param money  the value for inbound.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.tax
	 * @return  the value of inbound.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.tax
	 * @param tax  the value for inbound.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setTax(Double tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.money_with_tax
	 * @return  the value of inbound.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getMoneyWithTax() {
		return moneyWithTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.money_with_tax
	 * @param moneyWithTax  the value for inbound.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setMoneyWithTax(Double moneyWithTax) {
		this.moneyWithTax = moneyWithTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound.note
	 * @return  the value of inbound.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound.note
	 * @param note  the value for inbound.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setNote(String note) {
		this.note = note;
	}
}