package com.zd.testing.business.model;

import java.util.Date;

public class RepositoryDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_inbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer goodsInboundCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_inbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsInboundMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_inbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsInboundPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_outbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer goodsOutboundCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_outbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsOutboundMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_outbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsOutboundPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_balance_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer goodsBalanceCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_balance_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsBalanceMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.goods_balance_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double goodsBalancePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.create_time
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.inbound_iid
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer inboundIid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repository_details.outbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer outboundId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.id
	 * @return  the value of repository_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.id
	 * @param id  the value for repository_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_id
	 * @return  the value of repository_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_id
	 * @param goodsId  the value for repository_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_inbound_count
	 * @return  the value of repository_details.goods_inbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getGoodsInboundCount() {
		return goodsInboundCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_inbound_count
	 * @param goodsInboundCount  the value for repository_details.goods_inbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsInboundCount(Integer goodsInboundCount) {
		this.goodsInboundCount = goodsInboundCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_inbound_money
	 * @return  the value of repository_details.goods_inbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsInboundMoney() {
		return goodsInboundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_inbound_money
	 * @param goodsInboundMoney  the value for repository_details.goods_inbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsInboundMoney(Double goodsInboundMoney) {
		this.goodsInboundMoney = goodsInboundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_inbound_price
	 * @return  the value of repository_details.goods_inbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsInboundPrice() {
		return goodsInboundPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_inbound_price
	 * @param goodsInboundPrice  the value for repository_details.goods_inbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsInboundPrice(Double goodsInboundPrice) {
		this.goodsInboundPrice = goodsInboundPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_outbound_count
	 * @return  the value of repository_details.goods_outbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getGoodsOutboundCount() {
		return goodsOutboundCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_outbound_count
	 * @param goodsOutboundCount  the value for repository_details.goods_outbound_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsOutboundCount(Integer goodsOutboundCount) {
		this.goodsOutboundCount = goodsOutboundCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_outbound_money
	 * @return  the value of repository_details.goods_outbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsOutboundMoney() {
		return goodsOutboundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_outbound_money
	 * @param goodsOutboundMoney  the value for repository_details.goods_outbound_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsOutboundMoney(Double goodsOutboundMoney) {
		this.goodsOutboundMoney = goodsOutboundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_outbound_price
	 * @return  the value of repository_details.goods_outbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsOutboundPrice() {
		return goodsOutboundPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_outbound_price
	 * @param goodsOutboundPrice  the value for repository_details.goods_outbound_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsOutboundPrice(Double goodsOutboundPrice) {
		this.goodsOutboundPrice = goodsOutboundPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_balance_count
	 * @return  the value of repository_details.goods_balance_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getGoodsBalanceCount() {
		return goodsBalanceCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_balance_count
	 * @param goodsBalanceCount  the value for repository_details.goods_balance_count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsBalanceCount(Integer goodsBalanceCount) {
		this.goodsBalanceCount = goodsBalanceCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_balance_money
	 * @return  the value of repository_details.goods_balance_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsBalanceMoney() {
		return goodsBalanceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_balance_money
	 * @param goodsBalanceMoney  the value for repository_details.goods_balance_money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsBalanceMoney(Double goodsBalanceMoney) {
		this.goodsBalanceMoney = goodsBalanceMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.goods_balance_price
	 * @return  the value of repository_details.goods_balance_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getGoodsBalancePrice() {
		return goodsBalancePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.goods_balance_price
	 * @param goodsBalancePrice  the value for repository_details.goods_balance_price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsBalancePrice(Double goodsBalancePrice) {
		this.goodsBalancePrice = goodsBalancePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.create_time
	 * @return  the value of repository_details.create_time
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.create_time
	 * @param createTime  the value for repository_details.create_time
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.inbound_iid
	 * @return  the value of repository_details.inbound_iid
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getInboundIid() {
		return inboundIid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.inbound_iid
	 * @param inboundIid  the value for repository_details.inbound_iid
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setInboundIid(Integer inboundIid) {
		this.inboundIid = inboundIid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repository_details.outbound_id
	 * @return  the value of repository_details.outbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getOutboundId() {
		return outboundId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repository_details.outbound_id
	 * @param outboundId  the value for repository_details.outbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setOutboundId(Integer outboundId) {
		this.outboundId = outboundId;
	}
}