package com.zd.testing.business.model;

public class Unit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit.unit_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer unitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit.unit_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String unitName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit.id
	 * @return  the value of unit.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit.id
	 * @param id  the value for unit.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit.unit_id
	 * @return  the value of unit.unit_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit.unit_id
	 * @param unitId  the value for unit.unit_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit.unit_name
	 * @return  the value of unit.unit_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit.unit_name
	 * @param unitName  the value for unit.unit_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}
}