package com.zd.warehouse.business.model;

public class Branch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column branch.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column branch.branch_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String branchName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column branch.id
	 * @return  the value of branch.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column branch.id
	 * @param id  the value for branch.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column branch.branch_name
	 * @return  the value of branch.branch_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getBranchName() {
		return branchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column branch.branch_name
	 * @param branchName  the value for branch.branch_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
}