package com.zd.warehouse.business.model;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer categoryId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.id
	 * @return  the value of category.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.id
	 * @param id  the value for category.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.name
	 * @return  the value of category.name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.name
	 * @param name  the value for category.name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_id
	 * @return  the value of category.category_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_id
	 * @param categoryId  the value for category.category_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}
}