package com.zd.warehouse.business.model;

public class Dept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.dept_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.dept_address
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String deptAddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.id
	 * @return  the value of dept.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.id
	 * @param id  the value for dept.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.dept_name
	 * @return  the value of dept.dept_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.dept_name
	 * @param deptName  the value for dept.dept_name
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.dept_address
	 * @return  the value of dept.dept_address
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getDeptAddress() {
		return deptAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.dept_address
	 * @param deptAddress  the value for dept.dept_address
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setDeptAddress(String deptAddress) {
		this.deptAddress = deptAddress;
	}
}