package com.zd.warehouse.business.model;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.code
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.spec
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.branch_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer branchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.isspecific
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer isspecific;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pictureAdress
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String pictureadress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.code
     *
     * @return the value of goods.code
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.code
     *
     * @param code the value for goods.code
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.spec
     *
     * @return the value of goods.spec
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.spec
     *
     * @param spec the value for goods.spec
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category
     *
     * @return the value of goods.category
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category
     *
     * @param category the value for goods.category
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit_id
     *
     * @return the value of goods.unit_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit_id
     *
     * @param unitId the value for goods.unit_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.branch_id
     *
     * @return the value of goods.branch_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.branch_id
     *
     * @param branchId the value for goods.branch_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.isspecific
     *
     * @return the value of goods.isspecific
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getIsspecific() {
        return isspecific;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.isspecific
     *
     * @param isspecific the value for goods.isspecific
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setIsspecific(Integer isspecific) {
        this.isspecific = isspecific;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.note
     *
     * @return the value of goods.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.note
     *
     * @param note the value for goods.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pictureAdress
     *
     * @return the value of goods.pictureAdress
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getPictureadress() {
        return pictureadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pictureAdress
     *
     * @param pictureadress the value for goods.pictureAdress
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setPictureadress(String pictureadress) {
        this.pictureadress = pictureadress;
    }
}