package com.zd.warehouse.business.model;

public class InboundDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.inbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer inboundId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.tax_rate
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double taxRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private Double moneyWithTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inbound_details.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.id
	 * @return  the value of inbound_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.id
	 * @param id  the value for inbound_details.id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.inbound_id
	 * @return  the value of inbound_details.inbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getInboundId() {
		return inboundId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.inbound_id
	 * @param inboundId  the value for inbound_details.inbound_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setInboundId(Integer inboundId) {
		this.inboundId = inboundId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.goods_id
	 * @return  the value of inbound_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.goods_id
	 * @param goodsId  the value for inbound_details.goods_id
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.count
	 * @return  the value of inbound_details.count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.count
	 * @param count  the value for inbound_details.count
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.money
	 * @return  the value of inbound_details.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.money
	 * @param money  the value for inbound_details.money
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.price
	 * @return  the value of inbound_details.price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.price
	 * @param price  the value for inbound_details.price
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.tax_rate
	 * @return  the value of inbound_details.tax_rate
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getTaxRate() {
		return taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.tax_rate
	 * @param taxRate  the value for inbound_details.tax_rate
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setTaxRate(Double taxRate) {
		this.taxRate = taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.tax
	 * @return  the value of inbound_details.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.tax
	 * @param tax  the value for inbound_details.tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setTax(Double tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.money_with_tax
	 * @return  the value of inbound_details.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Double getMoneyWithTax() {
		return moneyWithTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.money_with_tax
	 * @param moneyWithTax  the value for inbound_details.money_with_tax
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setMoneyWithTax(Double moneyWithTax) {
		this.moneyWithTax = moneyWithTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inbound_details.note
	 * @return  the value of inbound_details.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inbound_details.note
	 * @param note  the value for inbound_details.note
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setNote(String note) {
		this.note = note;
	}
}