package com.zd.warehouse.business.model;

public class OutboundDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer outboundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.outbound_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer outboundCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.outbound_money
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Double outboundMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.outbound_price
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Double outboundPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.tax_rate
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Double taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Double tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.money_with_tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Double moneyWithTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound_details.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.id
     *
     * @return the value of outbound_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.id
     *
     * @param id the value for outbound_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.outbound_id
     *
     * @return the value of outbound_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getOutboundId() {
        return outboundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.outbound_id
     *
     * @param outboundId the value for outbound_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setOutboundId(Integer outboundId) {
        this.outboundId = outboundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.goods_id
     *
     * @return the value of outbound_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.goods_id
     *
     * @param goodsId the value for outbound_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.outbound_count
     *
     * @return the value of outbound_details.outbound_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getOutboundCount() {
        return outboundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.outbound_count
     *
     * @param outboundCount the value for outbound_details.outbound_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setOutboundCount(Integer outboundCount) {
        this.outboundCount = outboundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.outbound_money
     *
     * @return the value of outbound_details.outbound_money
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Double getOutboundMoney() {
        return outboundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.outbound_money
     *
     * @param outboundMoney the value for outbound_details.outbound_money
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setOutboundMoney(Double outboundMoney) {
        this.outboundMoney = outboundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.outbound_price
     *
     * @return the value of outbound_details.outbound_price
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Double getOutboundPrice() {
        return outboundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.outbound_price
     *
     * @param outboundPrice the value for outbound_details.outbound_price
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setOutboundPrice(Double outboundPrice) {
        this.outboundPrice = outboundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.tax_rate
     *
     * @return the value of outbound_details.tax_rate
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Double getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.tax_rate
     *
     * @param taxRate the value for outbound_details.tax_rate
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.tax
     *
     * @return the value of outbound_details.tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Double getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.tax
     *
     * @param tax the value for outbound_details.tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setTax(Double tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.money_with_tax
     *
     * @return the value of outbound_details.money_with_tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Double getMoneyWithTax() {
        return moneyWithTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.money_with_tax
     *
     * @param moneyWithTax the value for outbound_details.money_with_tax
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setMoneyWithTax(Double moneyWithTax) {
        this.moneyWithTax = moneyWithTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbound_details.note
     *
     * @return the value of outbound_details.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbound_details.note
     *
     * @param note the value for outbound_details.note
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}