package com.zd.warehouse.business.model;

import java.util.ArrayList;
import java.util.List;

public class OutboundDetailsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public OutboundDetailsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIsNull() {
			addCriterion("outbound_id is null");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIsNotNull() {
			addCriterion("outbound_id is not null");
			return (Criteria) this;
		}

		public Criteria andOutboundIdEqualTo(Integer value) {
			addCriterion("outbound_id =", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotEqualTo(Integer value) {
			addCriterion("outbound_id <>", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdGreaterThan(Integer value) {
			addCriterion("outbound_id >", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("outbound_id >=", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdLessThan(Integer value) {
			addCriterion("outbound_id <", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdLessThanOrEqualTo(Integer value) {
			addCriterion("outbound_id <=", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIn(List<Integer> values) {
			addCriterion("outbound_id in", values, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotIn(List<Integer> values) {
			addCriterion("outbound_id not in", values, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdBetween(Integer value1, Integer value2) {
			addCriterion("outbound_id between", value1, value2, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotBetween(Integer value1, Integer value2) {
			addCriterion("outbound_id not between", value1, value2,
					"outboundId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNull() {
			addCriterion("goods_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNotNull() {
			addCriterion("goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdEqualTo(Integer value) {
			addCriterion("goods_id =", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotEqualTo(Integer value) {
			addCriterion("goods_id <>", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThan(Integer value) {
			addCriterion("goods_id >", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_id >=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThan(Integer value) {
			addCriterion("goods_id <", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
			addCriterion("goods_id <=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIn(List<Integer> values) {
			addCriterion("goods_id in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotIn(List<Integer> values) {
			addCriterion("goods_id not in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
			addCriterion("goods_id between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
			addCriterion("goods_id not between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andOutboundCountIsNull() {
			addCriterion("outbound_count is null");
			return (Criteria) this;
		}

		public Criteria andOutboundCountIsNotNull() {
			addCriterion("outbound_count is not null");
			return (Criteria) this;
		}

		public Criteria andOutboundCountEqualTo(Integer value) {
			addCriterion("outbound_count =", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountNotEqualTo(Integer value) {
			addCriterion("outbound_count <>", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountGreaterThan(Integer value) {
			addCriterion("outbound_count >", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("outbound_count >=", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountLessThan(Integer value) {
			addCriterion("outbound_count <", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountLessThanOrEqualTo(Integer value) {
			addCriterion("outbound_count <=", value, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountIn(List<Integer> values) {
			addCriterion("outbound_count in", values, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountNotIn(List<Integer> values) {
			addCriterion("outbound_count not in", values, "outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountBetween(Integer value1, Integer value2) {
			addCriterion("outbound_count between", value1, value2,
					"outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("outbound_count not between", value1, value2,
					"outboundCount");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyIsNull() {
			addCriterion("outbound_money is null");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyIsNotNull() {
			addCriterion("outbound_money is not null");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyEqualTo(Double value) {
			addCriterion("outbound_money =", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyNotEqualTo(Double value) {
			addCriterion("outbound_money <>", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyGreaterThan(Double value) {
			addCriterion("outbound_money >", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("outbound_money >=", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyLessThan(Double value) {
			addCriterion("outbound_money <", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyLessThanOrEqualTo(Double value) {
			addCriterion("outbound_money <=", value, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyIn(List<Double> values) {
			addCriterion("outbound_money in", values, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyNotIn(List<Double> values) {
			addCriterion("outbound_money not in", values, "outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyBetween(Double value1, Double value2) {
			addCriterion("outbound_money between", value1, value2,
					"outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundMoneyNotBetween(Double value1, Double value2) {
			addCriterion("outbound_money not between", value1, value2,
					"outboundMoney");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceIsNull() {
			addCriterion("outbound_price is null");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceIsNotNull() {
			addCriterion("outbound_price is not null");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceEqualTo(Double value) {
			addCriterion("outbound_price =", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceNotEqualTo(Double value) {
			addCriterion("outbound_price <>", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceGreaterThan(Double value) {
			addCriterion("outbound_price >", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("outbound_price >=", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceLessThan(Double value) {
			addCriterion("outbound_price <", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceLessThanOrEqualTo(Double value) {
			addCriterion("outbound_price <=", value, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceIn(List<Double> values) {
			addCriterion("outbound_price in", values, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceNotIn(List<Double> values) {
			addCriterion("outbound_price not in", values, "outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceBetween(Double value1, Double value2) {
			addCriterion("outbound_price between", value1, value2,
					"outboundPrice");
			return (Criteria) this;
		}

		public Criteria andOutboundPriceNotBetween(Double value1, Double value2) {
			addCriterion("outbound_price not between", value1, value2,
					"outboundPrice");
			return (Criteria) this;
		}

		public Criteria andTaxRateIsNull() {
			addCriterion("tax_rate is null");
			return (Criteria) this;
		}

		public Criteria andTaxRateIsNotNull() {
			addCriterion("tax_rate is not null");
			return (Criteria) this;
		}

		public Criteria andTaxRateEqualTo(Double value) {
			addCriterion("tax_rate =", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotEqualTo(Double value) {
			addCriterion("tax_rate <>", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateGreaterThan(Double value) {
			addCriterion("tax_rate >", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateGreaterThanOrEqualTo(Double value) {
			addCriterion("tax_rate >=", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateLessThan(Double value) {
			addCriterion("tax_rate <", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateLessThanOrEqualTo(Double value) {
			addCriterion("tax_rate <=", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateIn(List<Double> values) {
			addCriterion("tax_rate in", values, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotIn(List<Double> values) {
			addCriterion("tax_rate not in", values, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateBetween(Double value1, Double value2) {
			addCriterion("tax_rate between", value1, value2, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotBetween(Double value1, Double value2) {
			addCriterion("tax_rate not between", value1, value2, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxIsNull() {
			addCriterion("tax is null");
			return (Criteria) this;
		}

		public Criteria andTaxIsNotNull() {
			addCriterion("tax is not null");
			return (Criteria) this;
		}

		public Criteria andTaxEqualTo(Double value) {
			addCriterion("tax =", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotEqualTo(Double value) {
			addCriterion("tax <>", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxGreaterThan(Double value) {
			addCriterion("tax >", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxGreaterThanOrEqualTo(Double value) {
			addCriterion("tax >=", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxLessThan(Double value) {
			addCriterion("tax <", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxLessThanOrEqualTo(Double value) {
			addCriterion("tax <=", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxIn(List<Double> values) {
			addCriterion("tax in", values, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotIn(List<Double> values) {
			addCriterion("tax not in", values, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxBetween(Double value1, Double value2) {
			addCriterion("tax between", value1, value2, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotBetween(Double value1, Double value2) {
			addCriterion("tax not between", value1, value2, "tax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxIsNull() {
			addCriterion("money_with_tax is null");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxIsNotNull() {
			addCriterion("money_with_tax is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxEqualTo(Double value) {
			addCriterion("money_with_tax =", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxNotEqualTo(Double value) {
			addCriterion("money_with_tax <>", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxGreaterThan(Double value) {
			addCriterion("money_with_tax >", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxGreaterThanOrEqualTo(Double value) {
			addCriterion("money_with_tax >=", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxLessThan(Double value) {
			addCriterion("money_with_tax <", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxLessThanOrEqualTo(Double value) {
			addCriterion("money_with_tax <=", value, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxIn(List<Double> values) {
			addCriterion("money_with_tax in", values, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxNotIn(List<Double> values) {
			addCriterion("money_with_tax not in", values, "moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxBetween(Double value1, Double value2) {
			addCriterion("money_with_tax between", value1, value2,
					"moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andMoneyWithTaxNotBetween(Double value1, Double value2) {
			addCriterion("money_with_tax not between", value1, value2,
					"moneyWithTax");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table outbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outbound_details
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 07 08:22:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}