package com.zd.warehouse.business.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RepositoryDetailsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public RepositoryDetailsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNull() {
			addCriterion("goods_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNotNull() {
			addCriterion("goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdEqualTo(Integer value) {
			addCriterion("goods_id =", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotEqualTo(Integer value) {
			addCriterion("goods_id <>", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThan(Integer value) {
			addCriterion("goods_id >", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_id >=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThan(Integer value) {
			addCriterion("goods_id <", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
			addCriterion("goods_id <=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIn(List<Integer> values) {
			addCriterion("goods_id in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotIn(List<Integer> values) {
			addCriterion("goods_id not in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
			addCriterion("goods_id between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
			addCriterion("goods_id not between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountIsNull() {
			addCriterion("goods_inbound_count is null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountIsNotNull() {
			addCriterion("goods_inbound_count is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountEqualTo(Integer value) {
			addCriterion("goods_inbound_count =", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountNotEqualTo(Integer value) {
			addCriterion("goods_inbound_count <>", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountGreaterThan(Integer value) {
			addCriterion("goods_inbound_count >", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_inbound_count >=", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountLessThan(Integer value) {
			addCriterion("goods_inbound_count <", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountLessThanOrEqualTo(Integer value) {
			addCriterion("goods_inbound_count <=", value, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountIn(List<Integer> values) {
			addCriterion("goods_inbound_count in", values, "goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountNotIn(List<Integer> values) {
			addCriterion("goods_inbound_count not in", values,
					"goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_inbound_count between", value1, value2,
					"goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_inbound_count not between", value1, value2,
					"goodsInboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyIsNull() {
			addCriterion("goods_inbound_money is null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyIsNotNull() {
			addCriterion("goods_inbound_money is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyEqualTo(Double value) {
			addCriterion("goods_inbound_money =", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyNotEqualTo(Double value) {
			addCriterion("goods_inbound_money <>", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyGreaterThan(Double value) {
			addCriterion("goods_inbound_money >", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_inbound_money >=", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyLessThan(Double value) {
			addCriterion("goods_inbound_money <", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyLessThanOrEqualTo(Double value) {
			addCriterion("goods_inbound_money <=", value, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyIn(List<Double> values) {
			addCriterion("goods_inbound_money in", values, "goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyNotIn(List<Double> values) {
			addCriterion("goods_inbound_money not in", values,
					"goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyBetween(Double value1, Double value2) {
			addCriterion("goods_inbound_money between", value1, value2,
					"goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundMoneyNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_inbound_money not between", value1, value2,
					"goodsInboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceIsNull() {
			addCriterion("goods_inbound_price is null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceIsNotNull() {
			addCriterion("goods_inbound_price is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceEqualTo(Double value) {
			addCriterion("goods_inbound_price =", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceNotEqualTo(Double value) {
			addCriterion("goods_inbound_price <>", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceGreaterThan(Double value) {
			addCriterion("goods_inbound_price >", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_inbound_price >=", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceLessThan(Double value) {
			addCriterion("goods_inbound_price <", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceLessThanOrEqualTo(Double value) {
			addCriterion("goods_inbound_price <=", value, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceIn(List<Double> values) {
			addCriterion("goods_inbound_price in", values, "goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceNotIn(List<Double> values) {
			addCriterion("goods_inbound_price not in", values,
					"goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceBetween(Double value1, Double value2) {
			addCriterion("goods_inbound_price between", value1, value2,
					"goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsInboundPriceNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_inbound_price not between", value1, value2,
					"goodsInboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountIsNull() {
			addCriterion("goods_outbound_count is null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountIsNotNull() {
			addCriterion("goods_outbound_count is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountEqualTo(Integer value) {
			addCriterion("goods_outbound_count =", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountNotEqualTo(Integer value) {
			addCriterion("goods_outbound_count <>", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountGreaterThan(Integer value) {
			addCriterion("goods_outbound_count >", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_outbound_count >=", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountLessThan(Integer value) {
			addCriterion("goods_outbound_count <", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountLessThanOrEqualTo(Integer value) {
			addCriterion("goods_outbound_count <=", value, "goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountIn(List<Integer> values) {
			addCriterion("goods_outbound_count in", values,
					"goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountNotIn(List<Integer> values) {
			addCriterion("goods_outbound_count not in", values,
					"goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_outbound_count between", value1, value2,
					"goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_outbound_count not between", value1, value2,
					"goodsOutboundCount");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyIsNull() {
			addCriterion("goods_outbound_money is null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyIsNotNull() {
			addCriterion("goods_outbound_money is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyEqualTo(Double value) {
			addCriterion("goods_outbound_money =", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyNotEqualTo(Double value) {
			addCriterion("goods_outbound_money <>", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyGreaterThan(Double value) {
			addCriterion("goods_outbound_money >", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_outbound_money >=", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyLessThan(Double value) {
			addCriterion("goods_outbound_money <", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyLessThanOrEqualTo(Double value) {
			addCriterion("goods_outbound_money <=", value, "goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyIn(List<Double> values) {
			addCriterion("goods_outbound_money in", values,
					"goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyNotIn(List<Double> values) {
			addCriterion("goods_outbound_money not in", values,
					"goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyBetween(Double value1,
				Double value2) {
			addCriterion("goods_outbound_money between", value1, value2,
					"goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundMoneyNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_outbound_money not between", value1, value2,
					"goodsOutboundMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceIsNull() {
			addCriterion("goods_outbound_price is null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceIsNotNull() {
			addCriterion("goods_outbound_price is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceEqualTo(Double value) {
			addCriterion("goods_outbound_price =", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceNotEqualTo(Double value) {
			addCriterion("goods_outbound_price <>", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceGreaterThan(Double value) {
			addCriterion("goods_outbound_price >", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_outbound_price >=", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceLessThan(Double value) {
			addCriterion("goods_outbound_price <", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceLessThanOrEqualTo(Double value) {
			addCriterion("goods_outbound_price <=", value, "goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceIn(List<Double> values) {
			addCriterion("goods_outbound_price in", values,
					"goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceNotIn(List<Double> values) {
			addCriterion("goods_outbound_price not in", values,
					"goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceBetween(Double value1,
				Double value2) {
			addCriterion("goods_outbound_price between", value1, value2,
					"goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsOutboundPriceNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_outbound_price not between", value1, value2,
					"goodsOutboundPrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountIsNull() {
			addCriterion("goods_balance_count is null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountIsNotNull() {
			addCriterion("goods_balance_count is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountEqualTo(Integer value) {
			addCriterion("goods_balance_count =", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountNotEqualTo(Integer value) {
			addCriterion("goods_balance_count <>", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountGreaterThan(Integer value) {
			addCriterion("goods_balance_count >", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_balance_count >=", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountLessThan(Integer value) {
			addCriterion("goods_balance_count <", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountLessThanOrEqualTo(Integer value) {
			addCriterion("goods_balance_count <=", value, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountIn(List<Integer> values) {
			addCriterion("goods_balance_count in", values, "goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountNotIn(List<Integer> values) {
			addCriterion("goods_balance_count not in", values,
					"goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_balance_count between", value1, value2,
					"goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("goods_balance_count not between", value1, value2,
					"goodsBalanceCount");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyIsNull() {
			addCriterion("goods_balance_money is null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyIsNotNull() {
			addCriterion("goods_balance_money is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyEqualTo(Double value) {
			addCriterion("goods_balance_money =", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyNotEqualTo(Double value) {
			addCriterion("goods_balance_money <>", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyGreaterThan(Double value) {
			addCriterion("goods_balance_money >", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_balance_money >=", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyLessThan(Double value) {
			addCriterion("goods_balance_money <", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyLessThanOrEqualTo(Double value) {
			addCriterion("goods_balance_money <=", value, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyIn(List<Double> values) {
			addCriterion("goods_balance_money in", values, "goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyNotIn(List<Double> values) {
			addCriterion("goods_balance_money not in", values,
					"goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyBetween(Double value1, Double value2) {
			addCriterion("goods_balance_money between", value1, value2,
					"goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalanceMoneyNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_balance_money not between", value1, value2,
					"goodsBalanceMoney");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceIsNull() {
			addCriterion("goods_balance_price is null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceIsNotNull() {
			addCriterion("goods_balance_price is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceEqualTo(Double value) {
			addCriterion("goods_balance_price =", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceNotEqualTo(Double value) {
			addCriterion("goods_balance_price <>", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceGreaterThan(Double value) {
			addCriterion("goods_balance_price >", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceGreaterThanOrEqualTo(Double value) {
			addCriterion("goods_balance_price >=", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceLessThan(Double value) {
			addCriterion("goods_balance_price <", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceLessThanOrEqualTo(Double value) {
			addCriterion("goods_balance_price <=", value, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceIn(List<Double> values) {
			addCriterion("goods_balance_price in", values, "goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceNotIn(List<Double> values) {
			addCriterion("goods_balance_price not in", values,
					"goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceBetween(Double value1, Double value2) {
			addCriterion("goods_balance_price between", value1, value2,
					"goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andGoodsBalancePriceNotBetween(Double value1,
				Double value2) {
			addCriterion("goods_balance_price not between", value1, value2,
					"goodsBalancePrice");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andInboundIidIsNull() {
			addCriterion("inbound_iid is null");
			return (Criteria) this;
		}

		public Criteria andInboundIidIsNotNull() {
			addCriterion("inbound_iid is not null");
			return (Criteria) this;
		}

		public Criteria andInboundIidEqualTo(Integer value) {
			addCriterion("inbound_iid =", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidNotEqualTo(Integer value) {
			addCriterion("inbound_iid <>", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidGreaterThan(Integer value) {
			addCriterion("inbound_iid >", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidGreaterThanOrEqualTo(Integer value) {
			addCriterion("inbound_iid >=", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidLessThan(Integer value) {
			addCriterion("inbound_iid <", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidLessThanOrEqualTo(Integer value) {
			addCriterion("inbound_iid <=", value, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidIn(List<Integer> values) {
			addCriterion("inbound_iid in", values, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidNotIn(List<Integer> values) {
			addCriterion("inbound_iid not in", values, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidBetween(Integer value1, Integer value2) {
			addCriterion("inbound_iid between", value1, value2, "inboundIid");
			return (Criteria) this;
		}

		public Criteria andInboundIidNotBetween(Integer value1, Integer value2) {
			addCriterion("inbound_iid not between", value1, value2,
					"inboundIid");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIsNull() {
			addCriterion("outbound_id is null");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIsNotNull() {
			addCriterion("outbound_id is not null");
			return (Criteria) this;
		}

		public Criteria andOutboundIdEqualTo(Integer value) {
			addCriterion("outbound_id =", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotEqualTo(Integer value) {
			addCriterion("outbound_id <>", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdGreaterThan(Integer value) {
			addCriterion("outbound_id >", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("outbound_id >=", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdLessThan(Integer value) {
			addCriterion("outbound_id <", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdLessThanOrEqualTo(Integer value) {
			addCriterion("outbound_id <=", value, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdIn(List<Integer> values) {
			addCriterion("outbound_id in", values, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotIn(List<Integer> values) {
			addCriterion("outbound_id not in", values, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdBetween(Integer value1, Integer value2) {
			addCriterion("outbound_id between", value1, value2, "outboundId");
			return (Criteria) this;
		}

		public Criteria andOutboundIdNotBetween(Integer value1, Integer value2) {
			addCriterion("outbound_id not between", value1, value2,
					"outboundId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table repository_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repository_details
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 07 08:22:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}