package com.zd.warehouse.business.model;

public class RepositoryDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_details.goods_balance_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer goodsBalanceCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_details.inbound_iid
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer inboundIid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer outboundId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_details.id
     *
     * @return the value of repository_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_details.id
     *
     * @param id the value for repository_details.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_details.goods_id
     *
     * @return the value of repository_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_details.goods_id
     *
     * @param goodsId the value for repository_details.goods_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_details.goods_balance_count
     *
     * @return the value of repository_details.goods_balance_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getGoodsBalanceCount() {
        return goodsBalanceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_details.goods_balance_count
     *
     * @param goodsBalanceCount the value for repository_details.goods_balance_count
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setGoodsBalanceCount(Integer goodsBalanceCount) {
        this.goodsBalanceCount = goodsBalanceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_details.inbound_iid
     *
     * @return the value of repository_details.inbound_iid
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getInboundIid() {
        return inboundIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_details.inbound_iid
     *
     * @param inboundIid the value for repository_details.inbound_iid
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setInboundIid(Integer inboundIid) {
        this.inboundIid = inboundIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_details.outbound_id
     *
     * @return the value of repository_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getOutboundId() {
        return outboundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_details.outbound_id
     *
     * @param outboundId the value for repository_details.outbound_id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setOutboundId(Integer outboundId) {
        this.outboundId = outboundId;
    }
}