package com.zd.warehouse.business.model;

public class Supplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.contact
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.phone
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private Integer phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.goods_address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String goodsAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.goods_type_id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private Integer goodsTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.note
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.id
	 * @return  the value of supplier.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.id
	 * @param id  the value for supplier.id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_name
	 * @return  the value of supplier.supplier_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_name
	 * @param supplierName  the value for supplier.supplier_name
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.contact
	 * @return  the value of supplier.contact
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.contact
	 * @param contact  the value for supplier.contact
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.address
	 * @return  the value of supplier.address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.address
	 * @param address  the value for supplier.address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.phone
	 * @return  the value of supplier.phone
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Integer getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.phone
	 * @param phone  the value for supplier.phone
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.goods_address
	 * @return  the value of supplier.goods_address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getGoodsAddress() {
		return goodsAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.goods_address
	 * @param goodsAddress  the value for supplier.goods_address
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setGoodsAddress(String goodsAddress) {
		this.goodsAddress = goodsAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.goods_type_id
	 * @return  the value of supplier.goods_type_id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public Integer getGoodsTypeId() {
		return goodsTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.goods_type_id
	 * @param goodsTypeId  the value for supplier.goods_type_id
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setGoodsTypeId(Integer goodsTypeId) {
		this.goodsTypeId = goodsTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.note
	 * @return  the value of supplier.note
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.note
	 * @param note  the value for supplier.note
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	public void setNote(String note) {
		this.note = note;
	}
}