package com.zd.warehouse.business.model;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    private String unitName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_name
     *
     * @return the value of unit.unit_name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_name
     *
     * @param unitName the value for unit.unit_name
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
}