package com.zd.warehouse.business.mapper;

import java.util.List;

import com.zd.warehouse.business.model.Branch;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    Branch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Mon Jun 11 15:19:40 CST 2018
     */
    int updateByPrimaryKey(Branch record);

	List<Branch> queryAllBranch();
}