package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.Dept;
import com.zd.warehouse.business.model.DeptExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int countByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insert(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insertSelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	List<Dept> selectByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	Dept selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Dept record,
			@Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExample(@Param("record") Dept record,
			@Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKeySelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKey(Dept record);
}