package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.InboundDetails;

public interface InboundDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insert(InboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insertSelective(InboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    InboundDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(InboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKey(InboundDetails record);
}