package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.Inbound;
import com.zd.warehouse.business.model.InboundExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InboundMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int countByExample(InboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByExample(InboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insert(Inbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insertSelective(Inbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	List<Inbound> selectByExample(InboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	Inbound selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Inbound record,
			@Param("example") InboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExample(@Param("record") Inbound record,
			@Param("example") InboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKeySelective(Inbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKey(Inbound record);
}