package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.Inbound;

public interface InboundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insert(Inbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insertSelective(Inbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    Inbound selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(Inbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKey(Inbound record);
}