package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.InboundDetails;
import com.zd.warehouse.business.model.InboundDetailsExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InboundDetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int countByExample(InboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByExample(InboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insert(InboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insertSelective(InboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	List<InboundDetails> selectByExample(InboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	InboundDetails selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") InboundDetails record,
			@Param("example") InboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExample(@Param("record") InboundDetails record,
			@Param("example") InboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKeySelective(InboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inbound_details
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKey(InboundDetails record);
}