package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.Outbound;
import com.zd.warehouse.business.model.OutboundExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OutboundMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int countByExample(OutboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByExample(OutboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insert(Outbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int insertSelective(Outbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	List<Outbound> selectByExample(OutboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	Outbound selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Outbound record,
			@Param("example") OutboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByExample(@Param("record") Outbound record,
			@Param("example") OutboundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKeySelective(Outbound record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound
	 * @mbggenerated  Fri Jun 08 15:35:41 CST 2018
	 */
	int updateByPrimaryKey(Outbound record);
}