package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.OutboundDetails;
import com.zd.warehouse.business.model.OutboundDetailsExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OutboundDetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int countByExample(OutboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int deleteByExample(OutboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int insert(OutboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int insertSelective(OutboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	List<OutboundDetails> selectByExample(OutboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	OutboundDetails selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int updateByExampleSelective(@Param("record") OutboundDetails record,
			@Param("example") OutboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int updateByExample(@Param("record") OutboundDetails record,
			@Param("example") OutboundDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int updateByPrimaryKeySelective(OutboundDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outbound_details
	 * @mbggenerated  Sat Jun 09 08:40:28 CST 2018
	 */
	int updateByPrimaryKey(OutboundDetails record);
}