package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.Outbound;

public interface OutboundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insert(Outbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insertSelective(Outbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    Outbound selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(Outbound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKey(Outbound record);
}