package com.zd.warehouse.business.mapper;

import com.zd.warehouse.business.model.OutboundDetails;

public interface OutboundDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insert(OutboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insertSelective(OutboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    OutboundDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(OutboundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbound_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKey(OutboundDetails record);
}