package com.zd.warehouse.business.mapper;

import java.util.List;

import com.zd.warehouse.business.model.RepositoryDetails;

public interface RepositoryDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insert(RepositoryDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int insertSelective(RepositoryDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    RepositoryDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(RepositoryDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_details
     *
     * @mbggenerated Mon Jun 11 15:19:39 CST 2018
     */
    int updateByPrimaryKey(RepositoryDetails record);

	List<RepositoryDetails> queryAll();

	int deleteRepository(List<String> list);
}